#!/usr/bin/env python3
"""Generate a comparison report for user dictionary cache on/off benchmarks.

Reads build_bench/{cache,nocache}/bench.raw (gtest + glog output) and the
optional time.txt from GNU time, then emits a Markdown table (default) or
machine-readable JSON (--json).

The benchmark logs lines such as:
    ...] Lookup (nhm) [LevelDB] +cache: 5.9 us
    ...] UpdateEntry (5000 entries) [LevelDB] -cache: 5 us per entry, ...
"""

import json
import re
import sys

LINE_RE = re.compile(r'^.*?\]\s+(.+?) \[LevelDB\] ([+-]cache): ([\d.]+) (us|ms)\b')
RSS_RE = re.compile(r'Maximum resident set size \(kbytes\): (\d+)')


def parse_log(path):
    """Return {metric: (value_us, unit, variant)} averaged over runs."""
    values = {}
    with open(path, encoding='utf-8', errors='replace') as f:
        for line in f:
            m = LINE_RE.search(line)
            if not m:
                continue
            metric, variant, val, unit = m.groups()
            value_us = float(val) * 1000.0 if unit == 'ms' else float(val)
            values.setdefault(metric, []).append((value_us, unit))
    result = {}
    for metric, samples in values.items():
        us = sum(s[0] for s in samples) / len(samples)
        result[metric] = (us, samples[0][1])
    return result


def parse_rss(path):
    if not path:
        return None
    try:
        with open(path, encoding='utf-8', errors='replace') as f:
            for line in f:
                m = RSS_RE.search(line)
                if m:
                    return int(m.group(1)) / 1024.0  # MB
    except OSError:
        return None
    return None


def fmt_value(value_us, unit):
    if unit == 'ms' or value_us >= 1000:
        return f'{value_us / 1000.0:.3g} ms'
    return f'{value_us:.3g} us'


def fmt_speedup(nocache_us, cache_us):
    if not cache_us:
        return 'n/a'
    ratio = nocache_us / cache_us
    if abs(ratio - 1.0) < 0.05:
        return '1.0x'
    return f'{ratio:.1f}x'


def main():
    if len(sys.argv) < 2:
        print('usage: bench_report.py <build_bench_dir> [--markdown|--json]',
              file=sys.stderr)
        return 2
    out_dir = sys.argv[1]
    fmt = '--json' if '--json' in sys.argv else '--markdown'

    cache = parse_log(f'{out_dir}/cache/bench.raw')
    nocache = parse_log(f'{out_dir}/nocache/bench.raw')
    rss_cache = parse_rss(f'{out_dir}/cache/time.txt')
    rss_nocache = parse_rss(f'{out_dir}/nocache/time.txt')

    metrics = [m for m in cache if m in nocache]
    # stable ordering: keep cache log order for non-[LevelDB]-only metrics
    cache_order = list(cache.keys())

    if fmt == '--json':
        rows = []
        for metric in cache_order:
            if metric not in cache or metric not in nocache:
                continue
            cache_us, unit = cache[metric]
            nocache_us, _ = nocache[metric]
            rows.append({
                'metric': metric,
                'cache_us': cache_us,
                'nocache_us': nocache_us,
                'speedup': round(nocache_us / cache_us, 2) if cache_us else None,
            })
        report = {
            'metrics': rows,
            'peak_rss_mb': {
                'cache': rss_cache,
                'nocache': rss_nocache,
            },
        }
        print(json.dumps(report, indent=2))
        return 0

    print('# User Dictionary Cache Benchmark')
    print()
    print('Comparison of `RIME_USER_DICT_CACHE_ENABLED=1` (cache) vs '
          '`=0` (no cache). Generated by `benchmark_compare.sh`.')
    print()
    print('| Metric | Cache | No cache | Speedup |')
    print('|---|---|---|---|')
    for metric in cache_order:
        if metric not in cache or metric not in nocache:
            continue
        cache_us, unit = cache[metric]
        nocache_us, _ = nocache[metric]
        print(f'| {metric} | {fmt_value(cache_us, unit)} | '
              f'{fmt_value(nocache_us, unit)} | {fmt_speedup(nocache_us, cache_us)} |')
    print()
    if rss_cache and rss_nocache:
        print('| Peak RSS | '
              f'{rss_cache:.1f} MB | {rss_nocache:.1f} MB | '
              f'{fmt_speedup(rss_nocache, rss_cache)} |')
    print()
    print('*Higher speedup (>1x) means the cache variant is faster '
          'than the no-cache variant.*')
    return 0


if __name__ == '__main__':
    sys.exit(main())
