find_path(YamlCpp_INCLUDE_PATH yaml-cpp/yaml.h)
find_library(YamlCpp_LIBRARY yaml-cpp)
find_library(YamlCpp_LIBRARY libyaml-cppmd)
find_library(YamlCpp_LIBRARY libyaml-cppmt)
if(YamlCpp_INCLUDE_PATH AND YamlCpp_LIBRARY)
  set(YamlCpp_FOUND TRUE)
endif(YamlCpp_INCLUDE_PATH AND YamlCpp_LIBRARY)
if(YamlCpp_FOUND)
  if(NOT YamlCpp_FIND_QUIETLY)
    message(STATUS "Found yaml-cpp: ${YamlCpp_LIBRARY}")
  endif(NOT YamlCpp_FIND_QUIETLY)
else(YamlCpp_FOUND)
  if(YamlCpp_FIND_REQUIRED)
    message(FATAL_ERROR "Could not find yaml-cpp library.")
  endif(YamlCpp_FIND_REQUIRED)
endif(YamlCpp_FOUND)
