find_path(Opencc_INCLUDE_PATH opencc/opencc.h)
find_library(Opencc_LIBRARY NAMES opencc)
if(Opencc_INCLUDE_PATH AND Opencc_LIBRARY)
  set(Opencc_FOUND TRUE)
endif(Opencc_INCLUDE_PATH AND Opencc_LIBRARY)
if(Opencc_FOUND)
  if(NOT Opencc_FIND_QUIETLY)
    message(STATUS "Found opencc: ${Opencc_LIBRARY}")
  endif(NOT Opencc_FIND_QUIETLY)
else(Opencc_FOUND)
  if(Opencc_FIND_REQUIRED)
    message(FATAL_ERROR "Could not find opencc library.")
  endif(Opencc_FIND_REQUIRED)
endif(Opencc_FOUND)
